name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    uses: MiningOrca/release-workflows/.github/workflows/macos-achievement-release.yml@main
    with:
      script_path: bg3-achievements-patch.sh
      asset_name: bg3-achievements-patch.sh
      label: PATCHING BG3...
    secrets:
      MINING_ORCA_TOKEN: ${{ secrets.MINING_ORCA_TOKEN }}
